const codeRouter = require('express').Router()
const axios = require('axios')

codeRouter.get('/:difficulty', async (req, res, next) => {
  const { difficulty } = req.params

  // Validate difficulty range
  if (difficulty > 6 || difficulty < 4) {
    return res.status(401).json({ error: 'invalid difficulty' })
  }

  // Fetch and parse code generated by API
  const baseUrl = `https://www.random.org/integers/?num=${difficulty}&min=0&max=7&col=1&base=10&format=plain`
  const apiResponse = await axios.get(baseUrl)
  const numbers = apiResponse.data
  const newNumbers = numbers.split('\n')
  const code = newNumbers.slice(0, difficulty)

  res.json(code)
})

module.exports = codeRouter
