const codeRouter = require('express').Router()
const axios = require('axios')

codeRouter.get('/:difficulty', async (req, res) => {
  const { difficulty } = req.params

  // Validate difficulty range
  if (difficulty > 6 || difficulty < 4) {
    const difficultyError = new Error('Difficulty must be within range of 4 to 6')
    difficultyError.name = 'InvalidDifficulty'
    throw difficultyError
  }

  // Fetch and parse code generated by API
  const baseUrl = `https://www.random.org/integers/?num=${difficulty}&min=0&max=7&col=1&base=10&format=plain`
  try {
    const apiResponse = await axios.get(baseUrl)
    const numbers = apiResponse.data
    const newNumbers = numbers.split('\n')
    const code = newNumbers.slice(0, difficulty)

    res.json(code)
  } catch (exception) {
    const error = new Error('API could not be reached')
    error.name = 'APIUnreacheable'
    error.difficulty = difficulty
    throw error
  }
})

module.exports = codeRouter
